language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
  - "pypy3"

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

env:
  - PY_COLORS=1 PYTHONPATH=.

install:
  - pip install -r requirements-ci.txt

script:
  - if [[ $TRAVIS_PYTHON_VERSION == pypy* ]]; then py.test; fi
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage run -m pytest --showlocals; fi
  - flake8 --max-line-length=100 --ignore=F403 --show-source
  - ! grep -orE --exclude-dir=.tox --exclude-dir=logs --exclude-dir=htmlcov "(FIXME|TODO|HACK):.*$" .

after_script:
  - python helpers/debug-info.py

after_success:
  - if [[ $TRAVIS_PYTHON_VERSION != pypy* ]]; then coverage combine && codecov; fi
